services :

  frontend :
    build : ./frontend
    ports :
      - "3000:3000"
    depends_on :
      - backend

  backend :
    build : ./backend
    ports :
      - "5000:5000"
    depends_on:
      - mysql

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  mysql :
    image : mysql:8
    ports : 
      - "3306"
    environment :
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

